name: Test

on:
  push:
    branches:
      - master

jobs:
  test:
    strategy:
      matrix:
        # go-version: [1.9.x, 1.10.x, 1.11.x, 1.12.x, 1.13.x, 1.14.x, 1.15.x]
        go-version: [1.10.x]
        platform: [windows-latest, ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v2


      - name: Test and generate coverage report
        run: |
          go test ./... -timeout 20m -race -run=Coverage -coverprofile c.out -covermode=atomic

      - name: LS
        run: |
          ls

      - name: Generage coverage.txt
        run: |
          mv c.out coverage.txt

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.txt
          flags: unittests
          fail_ci_if_error: true
